version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - persian-tts-network
    restart: always

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}/backend:${VERSION:-latest}
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      HF_TOKEN: ${HF_TOKEN}
      SENTRY_DSN: ${SENTRY_DSN}
    volumes:
      - /opt/persian-tts/models:/app/models
      - /opt/persian-tts/logs:/app/logs
    networks:
      - persian-tts-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    restart: always

  client:
    image: ghcr.io/${GITHUB_REPOSITORY}/client:${VERSION:-latest}
    networks:
      - persian-tts-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always

networks:
  persian-tts-network:
    driver: bridge
